// story-specs.mjs — 长上下文幻觉测试的合成小说内容源（change: add-long-context-hallucination-fixtures 任务 1.2/2.x）
//
// 本文件是「单一真相源」：每档（10k/30k/50k）的人物、地点、事实锚点（anchor）与查询（query）都写在这里。
// generator.mjs 只负责把这些内容确定性地编织成长文并产出材料与裁判元数据；validator 据此校验一致性。
//
// 锚点（anchor）的 statement 必须逐字写进材料正文，validator 会断言其在正文中出现。
// 查询（query）引用这些锚点，给出完整的事实边界（mustContain/mustNegate/wrongConclusions/allowedUncertainty）。
//
// 七个风险类别（与 manifest.risk_categories 一一对应）：
//   distant-recall       远距召回（早期事实埋得很深，需跨大量无关内容召回）
//   cross-chapter-relation 跨章关系（答案需拼接两个以上章节的事实）
//   similar-entity       相似实体（名字相近的人物/地点，需区分）
//   version-conflict     版本冲突（早期事实后来被更正，需依据最新事实）
//   unknown-fact         未知事实（材料未提供，应表达「未知/未提及」）
//   false-premise        错误前提纠正（问题自带错误前提，应纠正）
//   multi-turn-recall    多轮召回（经前置追问后召回材料事实）

export const STORY_SPECS = {
  "10k": {
    tier: "10k",
    title: "雾城长河",
    characters: [
      { name: "苏晚", role: "主角，盐镇人" },
      { name: "沈砚", role: "苏晚的表哥，雾港旧书修复师" },
      { name: "苏梅", role: "苏晚的母亲，盐镇杂货铺老板" },
      { name: "苏蔓", role: "苏晚的远房表妹，盐城茶馆老板" },
      { name: "陈屿", role: "城西出版社编辑，摄影展策展人" },
    ],
    places: ["盐镇", "盐城", "雾港", "城西的文化馆", "城东的画廊", "城西的出版社", "退潮后的滩涂", "旧码头"],
    objects: ["旧怀表", "泛黄的信", "老相机", "明信片", "油灯"],
    spots: ["码头", "巷口", "天台", "桥头", "窗边"],
    fillerTitles: ["雾城琐记", "海雾深处", "盐滩夜话", "长河旧事", "雾港来客"],
    chapters: [
      {
        number: 1,
        title: "盐镇来信",
        anchors: [
          { id: "a1", category: "distant-recall", entity: "苏晚", statement: "苏晚出生在海边的盐镇，那里常年被海雾笼罩。" },
          { id: "a2", category: "cross-chapter-relation", entity: "沈砚", statement: "沈砚是苏晚的表哥，是母亲这边的亲戚，在雾港做旧书修复。" },
          { id: "a3", category: "distant-recall", entity: "苏晚", statement: "苏晚小时候喜欢在退潮后的滩涂上捡贝壳。" },
        ],
      },
      {
        number: 2,
        title: "苏蔓的茶馆",
        anchors: [
          { id: "a4", category: "similar-entity", entity: "苏蔓", statement: "苏蔓是苏晚的远房表妹，三年前搬去了盐城，在城里开了一间茶馆。" },
          { id: "a5", category: "similar-entity", entity: "盐城", statement: "盐城和盐镇只隔着一片海湾，名字相近，许多人常把两地弄混。" },
        ],
      },
      {
        number: 3,
        title: "旧怀表",
        anchors: [
          { id: "a6", category: "multi-turn-recall", entity: "苏晚", statement: "苏晚在盐镇中学教语文，课间总把玩外婆留给她的那枚旧怀表。" },
        ],
      },
      {
        number: 4,
        title: "母亲",
        anchors: [
          { id: "a7", category: "cross-chapter-relation", entity: "苏梅", statement: "苏梅是苏晚的母亲，在盐镇开着一间小杂货铺。" },
        ],
      },
      {
        number: 5,
        title: "摄影展",
        anchors: [
          { id: "a8", category: "false-premise", entity: "苏晚", statement: "朋友曾建议苏晚把摄影展办在城东的画廊，但她最终选了城西的文化馆，展出了雾城系列，策展人是出版社编辑陈屿。" },
        ],
      },
      {
        number: 6,
        title: "换工作",
        anchors: [
          { id: "a9", category: "version-conflict", entity: "苏晚", statement: "苏晚辞去了盐镇中学的工作，去了城西的出版社做美术编辑，同事陈屿常和她一起加班。" },
        ],
      },
    ],
    queries: [
      {
        id: "lc-10k-01",
        category: "distant-recall",
        description: "远距召回：出生地埋在第一章开头，需跨越大量后续内容召回。",
        question: "苏晚的出生地是哪里？",
        expect: {
          factBoundary: { mustContain: ["盐镇"], mustNegate: [] },
          wrongConclusions: ["出生在盐城"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章"],
          riskTags: ["distant-recall"],
        },
      },
      {
        id: "lc-10k-02",
        category: "distant-recall",
        description: "远距召回：童年爱好埋在第一章，远离提问点。",
        question: "苏晚小时候喜欢做什么？",
        expect: {
          factBoundary: { mustContain: ["捡贝壳"], mustNegate: [] },
          wrongConclusions: ["钓鱼"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章"],
          riskTags: ["distant-recall"],
        },
      },
      {
        id: "lc-10k-03",
        category: "cross-chapter-relation",
        description: "跨章关系：沈砚是表哥（第一章）+ 苏梅是母亲（第四章），需拼接两章推出甥舅关系。",
        question: "沈砚和苏梅是什么关系？",
        expect: {
          factBoundary: { mustContain: ["外甥"], mustNegate: [] },
          wrongConclusions: ["侄子", "儿子"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章", "第四章"],
          riskTags: ["cross-chapter-relation"],
        },
      },
      {
        id: "lc-10k-04",
        category: "cross-chapter-relation",
        description: "跨章关系：陈屿在第五章以策展人出现、第六章以同事出现，需跨章还原其身份。",
        question: "陈屿是谁？",
        expect: {
          factBoundary: { mustContain: ["编辑"], mustNegate: [] },
          wrongConclusions: ["医生", "教师"],
          allowedUncertainty: [],
          evidenceLocations: ["第五章", "第六章"],
          riskTags: ["cross-chapter-relation"],
        },
      },
      {
        id: "lc-10k-05",
        category: "similar-entity",
        description: "相似实体：苏蔓住盐城，与苏晚住盐镇一字之差，需区分。",
        question: "苏蔓住在哪里？",
        expect: {
          factBoundary: { mustContain: ["盐城"], mustNegate: [] },
          wrongConclusions: ["住在盐镇"],
          allowedUncertainty: [],
          evidenceLocations: ["第二章"],
          riskTags: ["similar-entity"],
        },
      },
      {
        id: "lc-10k-06",
        category: "similar-entity",
        description: "相似实体：盐镇与盐城易混，苏晚住盐镇而非盐城。",
        question: "苏晚住在盐城吗？",
        expect: {
          factBoundary: { mustContain: ["盐镇"], mustNegate: ["住在盐城"] },
          wrongConclusions: ["住在盐城"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章", "第二章"],
          riskTags: ["similar-entity"],
        },
      },
      {
        id: "lc-10k-07",
        category: "version-conflict",
        description: "版本冲突：早期在盐镇中学教书（第三章），后来去了出版社（第六章），应依据最新事实。",
        question: "苏晚现在在哪里工作？",
        expect: {
          factBoundary: { mustContain: ["出版社"], mustNegate: [] },
          wrongConclusions: ["在盐镇中学教书"],
          allowedUncertainty: [],
          evidenceLocations: ["第六章"],
          riskTags: ["version-conflict"],
        },
      },
      {
        id: "lc-10k-08",
        category: "version-conflict",
        description: "版本冲突：工作已从盐镇中学变为出版社，应否定旧工作。",
        question: "苏晚现在还在盐镇中学教书吗？",
        expect: {
          factBoundary: { mustContain: ["出版社"], mustNegate: ["在盐镇中学教书"] },
          wrongConclusions: ["还在盐镇中学"],
          allowedUncertainty: [],
          evidenceLocations: ["第三章", "第六章"],
          riskTags: ["version-conflict"],
        },
      },
      {
        id: "lc-10k-09",
        category: "unknown-fact",
        description: "未知事实：材料从未提及苏晚的丈夫。",
        question: "苏晚的丈夫叫什么名字？",
        expect: {
          factBoundary: { mustContain: [], mustNegate: [] },
          wrongConclusions: [],
          allowedUncertainty: ["未知", "未提及"],
          evidenceLocations: ["全文"],
          riskTags: ["unknown-fact"],
        },
      },
      {
        id: "lc-10k-10",
        category: "unknown-fact",
        description: "未知事实：材料未给出苏晚的年龄。",
        question: "苏晚今年多少岁？",
        expect: {
          factBoundary: { mustContain: [], mustNegate: [] },
          wrongConclusions: [],
          allowedUncertainty: ["未知", "未提及"],
          evidenceLocations: ["全文"],
          riskTags: ["unknown-fact"],
        },
      },
      {
        id: "lc-10k-11",
        category: "false-premise",
        description: "错误前提纠正：问题误以为摄影展在城东的画廊，正确地点是城西的文化馆。",
        question: "苏晚的摄影展是在城东的画廊举办的吗？",
        expect: {
          factBoundary: { mustContain: ["城西的文化馆"], mustNegate: ["在城东的画廊举办"] },
          wrongConclusions: ["在城东的画廊举办"],
          allowedUncertainty: [],
          evidenceLocations: ["第五章"],
          riskTags: ["false-premise"],
        },
      },
      {
        id: "lc-10k-12",
        category: "multi-turn-recall",
        description: "多轮召回：经前置追问后召回怀表来源。",
        question: "苏晚的怀表是谁留给她的？",
        steps: [{ text: "我之前问过苏晚的怀表，你还记得吗？" }],
        expect: {
          factBoundary: { mustContain: ["外婆"], mustNegate: [] },
          wrongConclusions: ["母亲留给她的", "沈砚留给她的"],
          allowedUncertainty: [],
          evidenceLocations: ["第三章"],
          riskTags: ["multi-turn-recall"],
        },
      },
    ],
  },

  "30k": {
    tier: "30k",
    title: "回声旅馆",
    characters: [
      { name: "陆遥", role: "主角，摄影师" },
      { name: "江眠", role: "回声旅馆老板娘" },
      { name: "顾成", role: "陆遥的旧友，刑警" },
      { name: "陆远", role: "陆遥的弟弟，教师" },
      { name: "白露", role: "江眠的妹妹，策展人" },
      { name: "陆芸", role: "陆遥的母亲" },
      { name: "陆征", role: "陆遥的父亲，灯塔看守人" },
    ],
    places: ["白鹭镇", "白鹭洲", "回声旅馆", "云峰山", "旧码头", "城北的印刷厂", "城西的文化馆", "城东的画廊", "旧灯塔"],
    objects: ["老式相机", "旧信封", "怀表", "明信片", "油灯"],
    spots: ["码头", "山脚", "巷口", "天台", "桥头"],
    fillerTitles: ["回声絮语", "山雾漫记", "旅馆夜谈", "白鹭旧事", "码头来风"],
    chapters: [
      {
        number: 1,
        title: "白鹭镇的雾",
        anchors: [
          { id: "b1", category: "distant-recall", entity: "陆遥", statement: "陆遥出生在白鹭镇，镇外有一座废弃的旧灯塔。" },
          { id: "b2", category: "similar-entity", entity: "陆远", statement: "陆遥的弟弟陆远在白鹭洲教书，兄弟俩每年只聚一次。" },
          { id: "b3", category: "distant-recall", entity: "陆遥", statement: "陆遥小时候总爱去旧码头看潮水涨落。" },
        ],
      },
      {
        number: 2,
        title: "回声旅馆",
        anchors: [
          { id: "b4", category: "multi-turn-recall", entity: "江眠", statement: "江眠是回声旅馆的老板娘，旅馆坐落在云峰山脚下。" },
          { id: "b5", category: "similar-entity", entity: "白鹭洲", statement: "白鹭洲与白鹭镇相隔百里，名字相近，常被外地人认错。" },
        ],
      },
      {
        number: 3,
        title: "顾成来访",
        anchors: [
          { id: "b6", category: "cross-chapter-relation", entity: "顾成", statement: "顾成是陆遥的旧友，如今在云峰山一带做刑警。" },
          { id: "b7", category: "multi-turn-recall", entity: "陆遥", statement: "陆遥收藏着一台老式相机，是父亲留下的唯一遗物。" },
        ],
      },
      {
        number: 4,
        title: "母亲",
        anchors: [
          { id: "b8", category: "cross-chapter-relation", entity: "陆芸", statement: "陆遥的母亲叫陆芸，早年是白鹭镇小学的语文老师。" },
        ],
      },
      {
        number: 5,
        title: "换工作",
        anchors: [
          { id: "b9", category: "version-conflict", entity: "陆遥", statement: "陆遥原本在城北的印刷厂做排版，后来辞职去了云峰山下的摄影工作室。" },
          { id: "b10", category: "cross-chapter-relation", entity: "白露", statement: "白露是江眠的妹妹，在城西的文化馆工作。" },
        ],
      },
      {
        number: 6,
        title: "摄影展",
        anchors: [
          { id: "b11", category: "false-premise", entity: "陆遥", statement: "朋友曾劝陆遥把摄影展办在城东的画廊，但他最终选在城西的文化馆，策展人是白露。" },
        ],
      },
      {
        number: 7,
        title: "父亲",
        anchors: [
          { id: "b12", category: "distant-recall", entity: "陆征", statement: "陆遥的父亲叫陆征，曾是白鹭镇的灯塔看守人。" },
          { id: "b13", category: "cross-chapter-relation", entity: "顾成", statement: "顾成是陆芸的侄子，和陆遥从小一起长大。" },
        ],
      },
      {
        number: 8,
        title: "旧灯塔",
        anchors: [
          { id: "b14", category: "version-conflict", entity: "旧灯塔", statement: "那座废弃的旧灯塔去年被改造成了观景台，成了白鹭镇的新地标。" },
        ],
      },
    ],
    queries: [
      {
        id: "lc-30k-01",
        category: "distant-recall",
        description: "远距召回：出生地埋在第一章。",
        question: "陆遥的出生地是哪里？",
        expect: {
          factBoundary: { mustContain: ["白鹭镇"], mustNegate: [] },
          wrongConclusions: ["出生在白鹭洲"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章"],
          riskTags: ["distant-recall"],
        },
      },
      {
        id: "lc-30k-02",
        category: "distant-recall",
        description: "远距召回：童年习惯埋在第一章。",
        question: "陆遥小时候喜欢做什么？",
        expect: {
          factBoundary: { mustContain: ["看潮水"], mustNegate: [] },
          wrongConclusions: ["钓鱼", "放风筝"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章"],
          riskTags: ["distant-recall"],
        },
      },
      {
        id: "lc-30k-03",
        category: "distant-recall",
        description: "远距召回：父亲职业埋在第七章。",
        question: "陆遥的父亲是做什么的？",
        expect: {
          factBoundary: { mustContain: ["灯塔看守人"], mustNegate: [] },
          wrongConclusions: ["渔民", "教师"],
          allowedUncertainty: [],
          evidenceLocations: ["第七章"],
          riskTags: ["distant-recall"],
        },
      },
      {
        id: "lc-30k-04",
        category: "cross-chapter-relation",
        description: "跨章关系：陆远是弟弟（第一章）+ 陆芸是母亲（第四章），推出母子关系。",
        question: "陆远和陆芸是什么关系？",
        expect: {
          factBoundary: { mustContain: ["儿子"], mustNegate: [] },
          wrongConclusions: ["兄弟", "外甥"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章", "第四章"],
          riskTags: ["cross-chapter-relation"],
        },
      },
      {
        id: "lc-30k-05",
        category: "cross-chapter-relation",
        description: "跨章关系：顾成在第三章出场、第七章点明与陆芸的侄甥关系。",
        question: "顾成和陆芸是什么关系？",
        expect: {
          factBoundary: { mustContain: ["侄子"], mustNegate: [] },
          wrongConclusions: ["儿子", "外甥"],
          allowedUncertainty: [],
          evidenceLocations: ["第三章", "第七章"],
          riskTags: ["cross-chapter-relation"],
        },
      },
      {
        id: "lc-30k-06",
        category: "cross-chapter-relation",
        description: "跨章关系：白露第五章为文化馆工作人员、第六章为策展人，需跨章还原身份。",
        question: "白露是谁？",
        expect: {
          factBoundary: { mustContain: ["策展人"], mustNegate: [] },
          wrongConclusions: ["医生", "演员"],
          allowedUncertainty: [],
          evidenceLocations: ["第五章", "第六章"],
          riskTags: ["cross-chapter-relation"],
        },
      },
      {
        id: "lc-30k-07",
        category: "similar-entity",
        description: "相似实体：陆远住白鹭洲，与陆遥住白鹭镇一字之差。",
        question: "陆远住在哪里？",
        expect: {
          factBoundary: { mustContain: ["白鹭洲"], mustNegate: [] },
          wrongConclusions: ["住在白鹭镇"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章"],
          riskTags: ["similar-entity"],
        },
      },
      {
        id: "lc-30k-08",
        category: "similar-entity",
        description: "相似实体：白鹭镇与白鹭洲易混，陆遥住白鹭镇而非白鹭洲。",
        question: "陆遥住在白鹭洲吗？",
        expect: {
          factBoundary: { mustContain: ["白鹭镇"], mustNegate: ["住在白鹭洲"] },
          wrongConclusions: ["住在白鹭洲"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章", "第二章"],
          riskTags: ["similar-entity"],
        },
      },
      {
        id: "lc-30k-09",
        category: "similar-entity",
        description: "相似实体：陆远教书，与陆遥摄影不同，需区分兄弟二人。",
        question: "陆远是做什么的？",
        expect: {
          factBoundary: { mustContain: ["教书"], mustNegate: [] },
          wrongConclusions: ["摄影", "警察"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章"],
          riskTags: ["similar-entity"],
        },
      },
      {
        id: "lc-30k-10",
        category: "version-conflict",
        description: "版本冲突：早期在印刷厂，后来去了摄影工作室。",
        question: "陆遥现在在哪里工作？",
        expect: {
          factBoundary: { mustContain: ["摄影工作室"], mustNegate: [] },
          wrongConclusions: ["在印刷厂工作"],
          allowedUncertainty: [],
          evidenceLocations: ["第五章"],
          riskTags: ["version-conflict"],
        },
      },
      {
        id: "lc-30k-11",
        category: "version-conflict",
        description: "版本冲突：已离开印刷厂，应否定旧工作。",
        question: "陆遥现在还在印刷厂工作吗？",
        expect: {
          factBoundary: { mustContain: ["摄影工作室"], mustNegate: ["在印刷厂工作"] },
          wrongConclusions: ["还在印刷厂"],
          allowedUncertainty: [],
          evidenceLocations: ["第五章"],
          riskTags: ["version-conflict"],
        },
      },
      {
        id: "lc-30k-12",
        category: "version-conflict",
        description: "版本冲突：旧灯塔已改为观景台（第一章 vs 第八章）。",
        question: "旧灯塔现在是什么？",
        expect: {
          factBoundary: { mustContain: ["观景台"], mustNegate: [] },
          wrongConclusions: ["还是灯塔"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章", "第八章"],
          riskTags: ["version-conflict"],
        },
      },
      {
        id: "lc-30k-13",
        category: "unknown-fact",
        description: "未知事实：材料未提及陆遥的妻子。",
        question: "陆遥的妻子叫什么名字？",
        expect: {
          factBoundary: { mustContain: [], mustNegate: [] },
          wrongConclusions: [],
          allowedUncertainty: ["未知", "未提及"],
          evidenceLocations: ["全文"],
          riskTags: ["unknown-fact"],
        },
      },
      {
        id: "lc-30k-14",
        category: "unknown-fact",
        description: "未知事实：材料未给出陆遥的年龄。",
        question: "陆遥今年多大年纪？",
        expect: {
          factBoundary: { mustContain: [], mustNegate: [] },
          wrongConclusions: [],
          allowedUncertainty: ["未知", "未提及"],
          evidenceLocations: ["全文"],
          riskTags: ["unknown-fact"],
        },
      },
      {
        id: "lc-30k-15",
        category: "false-premise",
        description: "错误前提纠正：问题误以为摄影展在城东的画廊，正确地点是城西的文化馆。",
        question: "陆遥的摄影展是在城东的画廊举办的吗？",
        expect: {
          factBoundary: { mustContain: ["城西的文化馆"], mustNegate: ["在城东的画廊举办"] },
          wrongConclusions: ["在城东的画廊举办"],
          allowedUncertainty: [],
          evidenceLocations: ["第六章"],
          riskTags: ["false-premise"],
        },
      },
      {
        id: "lc-30k-16",
        category: "false-premise",
        description: "错误前提纠正：相机是父亲留下的，而非母亲。",
        question: "那台老式相机是母亲留给陆遥的吗？",
        expect: {
          factBoundary: { mustContain: ["父亲"], mustNegate: ["母亲留下的"] },
          wrongConclusions: ["母亲留下的"],
          allowedUncertainty: [],
          evidenceLocations: ["第三章"],
          riskTags: ["false-premise"],
        },
      },
      {
        id: "lc-30k-17",
        category: "multi-turn-recall",
        description: "多轮召回：经前置追问后召回相机来源。",
        question: "陆遥的相机是谁留给他的？",
        steps: [{ text: "我之前问过陆遥的相机，你还记得吗？" }],
        expect: {
          factBoundary: { mustContain: ["父亲"], mustNegate: [] },
          wrongConclusions: ["母亲留下的", "顾成留下的"],
          allowedUncertainty: [],
          evidenceLocations: ["第三章"],
          riskTags: ["multi-turn-recall"],
        },
      },
      {
        id: "lc-30k-18",
        category: "multi-turn-recall",
        description: "多轮召回：经前置追问后召回旅馆老板娘。",
        question: "回声旅馆的老板娘是谁？",
        steps: [{ text: "你前面提到了回声旅馆，能再想想吗？" }],
        expect: {
          factBoundary: { mustContain: ["江眠"], mustNegate: [] },
          wrongConclusions: ["老板娘是陆芸", "老板娘是白露"],
          allowedUncertainty: [],
          evidenceLocations: ["第二章"],
          riskTags: ["multi-turn-recall"],
        },
      },
    ],
  },

  "50k": {
    tier: "50k",
    title: "北境邮差",
    characters: [
      { name: "陈渡", role: "主角，邮差" },
      { name: "沈青梧", role: "青梧医馆医生" },
      { name: "阿黎", role: "陈渡的妹妹，教师" },
      { name: "陈桂芳", role: "陈渡的母亲，旧货铺老板" },
      { name: "陈大川", role: "陈渡的父亲，猎户" },
      { name: "小满", role: "青梧医馆学徒" },
    ],
    places: ["望山集", "望山岗", "鹿角镇", "青梧医馆", "北境雪原", "城西的邮局", "城南的旧货铺", "城东的当铺", "结冰的河"],
    objects: ["旧怀表", "父亲的信", "邮包", "油灯", "毛线围巾"],
    spots: ["雪原", "山脚", "巷口", "河岸", "桥头"],
    fillerTitles: ["北境记事", "雪原邮路", "望山夜话", "鹿角来客", "旧铺杂谈"],
    chapters: [
      {
        number: 1,
        title: "望山集的雪",
        anchors: [
          { id: "c1", category: "distant-recall", entity: "陈渡", statement: "陈渡出生在望山集，那里冬天会下很厚的雪。" },
          { id: "c2", category: "similar-entity", entity: "阿黎", statement: "陈渡的妹妹阿黎在望山岗教书，兄妹俩靠书信往来。" },
          { id: "c3", category: "distant-recall", entity: "陈渡", statement: "陈渡小时候喜欢在结冰的河面上滑冰。" },
        ],
      },
      {
        number: 2,
        title: "邮路",
        anchors: [
          { id: "c4", category: "distant-recall", entity: "陈渡", statement: "陈渡是北境的一名邮差，负责鹿角镇到望山集之间的邮路。" },
        ],
      },
      {
        number: 3,
        title: "青梧医馆",
        anchors: [
          { id: "c5", category: "multi-turn-recall", entity: "沈青梧", statement: "沈青梧是青梧医馆的医生，医馆开在鹿角镇。" },
          { id: "c6", category: "false-premise", entity: "陈渡", statement: "陈渡有一块旧怀表，是父亲留给他的。" },
        ],
      },
      {
        number: 4,
        title: "母亲",
        anchors: [
          { id: "c7", category: "cross-chapter-relation", entity: "陈桂芳", statement: "陈渡的母亲叫陈桂芳，在望山集经营一家旧货铺。" },
        ],
      },
      {
        number: 5,
        title: "换工作",
        anchors: [
          { id: "c8", category: "version-conflict", entity: "陈渡", statement: "陈渡原本在城西的邮局做分拣，后来主动申请调去了偏远的鹿角镇邮路。" },
        ],
      },
      {
        number: 6,
        title: "父亲的信",
        anchors: [
          { id: "c9", category: "distant-recall", entity: "陈大川", statement: "陈渡的父亲叫陈大川，曾是北境的一名猎户。" },
          { id: "c10", category: "false-premise", entity: "陈渡", statement: "父亲留下的那封信，陈渡一直没拆，信封已经泛黄。" },
        ],
      },
      {
        number: 7,
        title: "医馆学徒",
        anchors: [
          { id: "c11", category: "cross-chapter-relation", entity: "小满", statement: "小满是青梧医馆的学徒，跟着沈青梧学医已经三年。" },
        ],
      },
      {
        number: 8,
        title: "相似地点",
        anchors: [
          { id: "c12", category: "similar-entity", entity: "望山岗", statement: "望山岗和望山集相隔很远，名字相近，常被寄错信。" },
        ],
      },
      {
        number: 9,
        title: "当铺",
        anchors: [
          { id: "c13", category: "false-premise", entity: "陈渡", statement: "陈渡曾想把旧怀表拿去城东的当铺换钱，犹豫再三，还是没有去。" },
        ],
      },
      {
        number: 10,
        title: "老磨坊",
        anchors: [
          { id: "c14", category: "version-conflict", entity: "鹿角镇", statement: "鹿角镇那座废弃的老磨坊去年被改成了邮局的仓库。" },
        ],
      },
      {
        number: 11,
        title: "阿黎来信",
        anchors: [
          { id: "c15", category: "similar-entity", entity: "阿黎", statement: "阿黎在信里说，望山岗的学校只有她一个老师。" },
        ],
      },
      {
        number: 12,
        title: "沈青梧的身世",
        anchors: [
          { id: "c16", category: "cross-chapter-relation", entity: "沈青梧", statement: "沈青梧是陈桂芳的外甥女，小时候常来旧货铺帮忙。" },
        ],
      },
      {
        number: 13,
        title: "小满的来历",
        anchors: [
          { id: "c17", category: "cross-chapter-relation", entity: "小满", statement: "小满是沈青梧的侄子，从城里来投奔她学医。" },
        ],
      },
    ],
    queries: [
      {
        id: "lc-50k-01",
        category: "distant-recall",
        description: "远距召回：出生地埋在第一章。",
        question: "陈渡的出生地是哪里？",
        expect: {
          factBoundary: { mustContain: ["望山集"], mustNegate: [] },
          wrongConclusions: ["出生在望山岗"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章"],
          riskTags: ["distant-recall"],
        },
      },
      {
        id: "lc-50k-02",
        category: "distant-recall",
        description: "远距召回：童年爱好埋在第一章。",
        question: "陈渡小时候喜欢做什么？",
        expect: {
          factBoundary: { mustContain: ["滑冰"], mustNegate: [] },
          wrongConclusions: ["滑雪", "钓鱼"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章"],
          riskTags: ["distant-recall"],
        },
      },
      {
        id: "lc-50k-03",
        category: "distant-recall",
        description: "远距召回：父亲职业埋在第六章。",
        question: "陈渡的父亲是做什么的？",
        expect: {
          factBoundary: { mustContain: ["猎户"], mustNegate: [] },
          wrongConclusions: ["渔夫", "木匠"],
          allowedUncertainty: [],
          evidenceLocations: ["第六章"],
          riskTags: ["distant-recall"],
        },
      },
      {
        id: "lc-50k-04",
        category: "distant-recall",
        description: "远距召回：职业埋在第二章。",
        question: "陈渡的职业是什么？",
        expect: {
          factBoundary: { mustContain: ["邮差"], mustNegate: [] },
          wrongConclusions: ["医生", "教师"],
          allowedUncertainty: [],
          evidenceLocations: ["第二章"],
          riskTags: ["distant-recall"],
        },
      },
      {
        id: "lc-50k-05",
        category: "cross-chapter-relation",
        description: "跨章关系：阿黎是妹妹（第一章）+ 陈桂芳是母亲（第四章），推出母女关系。",
        question: "阿黎和陈桂芳是什么关系？",
        expect: {
          factBoundary: { mustContain: ["女儿"], mustNegate: [] },
          wrongConclusions: ["儿媳", "外甥女"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章", "第四章"],
          riskTags: ["cross-chapter-relation"],
        },
      },
      {
        id: "lc-50k-06",
        category: "cross-chapter-relation",
        description: "跨章关系：沈青梧与陈桂芳的甥舅关系在第十二章点明。",
        question: "沈青梧和陈桂芳是什么关系？",
        expect: {
          factBoundary: { mustContain: ["外甥女"], mustNegate: [] },
          wrongConclusions: ["女儿", "儿媳"],
          allowedUncertainty: [],
          evidenceLocations: ["第四章", "第十二章"],
          riskTags: ["cross-chapter-relation"],
        },
      },
      {
        id: "lc-50k-07",
        category: "cross-chapter-relation",
        description: "跨章关系：小满第七章为学徒、第十三章为侄子，需跨章还原身份。",
        question: "小满和沈青梧是什么关系？",
        expect: {
          factBoundary: { mustContain: ["侄子"], mustNegate: [] },
          wrongConclusions: ["儿子", "徒弟"],
          allowedUncertainty: [],
          evidenceLocations: ["第七章", "第十三章"],
          riskTags: ["cross-chapter-relation"],
        },
      },
      {
        id: "lc-50k-08",
        category: "cross-chapter-relation",
        description: "跨章关系：沈青梧在第三章出场为医生、第十二章点明与陈桂芳关系。",
        question: "沈青梧是谁？",
        expect: {
          factBoundary: { mustContain: ["医生"], mustNegate: [] },
          wrongConclusions: ["教师", "邮差"],
          allowedUncertainty: [],
          evidenceLocations: ["第三章", "第十二章"],
          riskTags: ["cross-chapter-relation"],
        },
      },
      {
        id: "lc-50k-09",
        category: "similar-entity",
        description: "相似实体：阿黎住望山岗，与陈渡住望山集一字之差。",
        question: "阿黎住在哪里？",
        expect: {
          factBoundary: { mustContain: ["望山岗"], mustNegate: [] },
          wrongConclusions: ["住在望山集"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章"],
          riskTags: ["similar-entity"],
        },
      },
      {
        id: "lc-50k-10",
        category: "similar-entity",
        description: "相似实体：望山集与望山岗易混，陈渡住望山集而非望山岗。",
        question: "陈渡住在望山岗吗？",
        expect: {
          factBoundary: { mustContain: ["望山集"], mustNegate: ["住在望山岗"] },
          wrongConclusions: ["住在望山岗"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章", "第八章"],
          riskTags: ["similar-entity"],
        },
      },
      {
        id: "lc-50k-11",
        category: "similar-entity",
        description: "相似实体：阿黎教书，与陈渡邮差不同，需区分兄妹二人。",
        question: "阿黎是做什么的？",
        expect: {
          factBoundary: { mustContain: ["老师"], mustNegate: [] },
          wrongConclusions: ["邮差"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章", "第十一章"],
          riskTags: ["similar-entity"],
        },
      },
      {
        id: "lc-50k-12",
        category: "similar-entity",
        description: "相似实体：陈渡的妹妹是阿黎，需与医馆学徒小满等其他人物区分。",
        question: "陈渡的妹妹叫什么名字？",
        expect: {
          factBoundary: { mustContain: ["阿黎"], mustNegate: [] },
          wrongConclusions: ["妹妹叫小满", "妹妹叫沈青梧"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章"],
          riskTags: ["similar-entity"],
        },
      },
      {
        id: "lc-50k-13",
        category: "version-conflict",
        description: "版本冲突：早期在城西邮局分拣，后来调到鹿角镇邮路。",
        question: "陈渡现在负责哪里的邮路？",
        expect: {
          factBoundary: { mustContain: ["鹿角镇"], mustNegate: [] },
          wrongConclusions: ["在城西的邮局工作"],
          allowedUncertainty: [],
          evidenceLocations: ["第二章", "第五章"],
          riskTags: ["version-conflict"],
        },
      },
      {
        id: "lc-50k-14",
        category: "version-conflict",
        description: "版本冲突：已离开城西邮局，应否定旧岗位。",
        question: "陈渡现在还在城西的邮局工作吗？",
        expect: {
          factBoundary: { mustContain: ["鹿角镇"], mustNegate: ["在城西的邮局工作"] },
          wrongConclusions: ["还在城西的邮局"],
          allowedUncertainty: [],
          evidenceLocations: ["第五章"],
          riskTags: ["version-conflict"],
        },
      },
      {
        id: "lc-50k-15",
        category: "version-conflict",
        description: "版本冲突：老磨坊已改为邮局仓库。",
        question: "鹿角镇的老磨坊现在是什么？",
        expect: {
          factBoundary: { mustContain: ["仓库"], mustNegate: [] },
          wrongConclusions: ["还是磨坊"],
          allowedUncertainty: [],
          evidenceLocations: ["第十章"],
          riskTags: ["version-conflict"],
        },
      },
      {
        id: "lc-50k-16",
        category: "unknown-fact",
        description: "未知事实：材料未提及陈渡的妻子。",
        question: "陈渡的妻子叫什么名字？",
        expect: {
          factBoundary: { mustContain: [], mustNegate: [] },
          wrongConclusions: [],
          allowedUncertainty: ["未知", "未提及"],
          evidenceLocations: ["全文"],
          riskTags: ["unknown-fact"],
        },
      },
      {
        id: "lc-50k-17",
        category: "unknown-fact",
        description: "未知事实：材料未给出陈渡的年龄。",
        question: "陈渡今年多大年纪？",
        expect: {
          factBoundary: { mustContain: [], mustNegate: [] },
          wrongConclusions: [],
          allowedUncertainty: ["未知", "未提及"],
          evidenceLocations: ["全文"],
          riskTags: ["unknown-fact"],
        },
      },
      {
        id: "lc-50k-18",
        category: "unknown-fact",
        description: "未知事实：材料未说明医馆的经营年限。",
        question: "青梧医馆开了多少年？",
        expect: {
          factBoundary: { mustContain: [], mustNegate: [] },
          wrongConclusions: [],
          allowedUncertainty: ["未知", "未提及"],
          evidenceLocations: ["全文"],
          riskTags: ["unknown-fact"],
        },
      },
      {
        id: "lc-50k-19",
        category: "false-premise",
        description: "错误前提纠正：怀表是父亲留下的，而非母亲。",
        question: "陈渡的旧怀表是母亲留给他的吗？",
        expect: {
          factBoundary: { mustContain: ["父亲"], mustNegate: ["母亲留给他的"] },
          wrongConclusions: ["母亲留给他的"],
          allowedUncertainty: [],
          evidenceLocations: ["第三章", "第四章"],
          riskTags: ["false-premise"],
        },
      },
      {
        id: "lc-50k-20",
        category: "false-premise",
        description: "错误前提纠正：问题误以为陈渡在望山岗负责邮路，实际是鹿角镇。",
        question: "陈渡是在望山岗负责邮路的吗？",
        expect: {
          factBoundary: { mustContain: ["鹿角镇"], mustNegate: ["在望山岗负责邮路"] },
          wrongConclusions: ["在望山岗负责邮路"],
          allowedUncertainty: [],
          evidenceLocations: ["第二章"],
          riskTags: ["false-premise"],
        },
      },
      {
        id: "lc-50k-21",
        category: "false-premise",
        description: "错误前提纠正：信从未拆开。",
        question: "陈渡把父亲留下的信拆开看了吗？",
        expect: {
          factBoundary: { mustContain: ["没拆"], mustNegate: ["拆开"] },
          wrongConclusions: ["拆开看了"],
          allowedUncertainty: [],
          evidenceLocations: ["第六章"],
          riskTags: ["false-premise"],
        },
      },
      {
        id: "lc-50k-22",
        category: "multi-turn-recall",
        description: "多轮召回：经前置追问后召回怀表来源。",
        question: "陈渡的怀表是谁留给他的？",
        steps: [{ text: "我之前问过陈渡的怀表，你还记得吗？" }],
        expect: {
          factBoundary: { mustContain: ["父亲"], mustNegate: [] },
          wrongConclusions: ["母亲留给他的", "沈青梧留给他的"],
          allowedUncertainty: [],
          evidenceLocations: ["第三章"],
          riskTags: ["multi-turn-recall"],
        },
      },
      {
        id: "lc-50k-23",
        category: "multi-turn-recall",
        description: "多轮召回：经前置追问后召回医馆医生。",
        question: "青梧医馆的医生是谁？",
        steps: [{ text: "你前面提到了青梧医馆，能再想想吗？" }],
        expect: {
          factBoundary: { mustContain: ["沈青梧"], mustNegate: [] },
          wrongConclusions: ["医生是小满", "医生是陈桂芳"],
          allowedUncertainty: [],
          evidenceLocations: ["第三章"],
          riskTags: ["multi-turn-recall"],
        },
      },
      {
        id: "lc-50k-24",
        category: "multi-turn-recall",
        description: "多轮召回：经前置追问后召回父亲姓名。",
        question: "陈渡的父亲叫什么名字？",
        steps: [{ text: "之前聊过陈渡的父亲，再帮我回忆一下。" }],
        expect: {
          factBoundary: { mustContain: ["陈大川"], mustNegate: [] },
          wrongConclusions: ["父亲叫陈桂芳", "父亲叫陈渡"],
          allowedUncertainty: [],
          evidenceLocations: ["第六章"],
          riskTags: ["multi-turn-recall"],
        },
      },
    ],
  },

  "coherent-10k": {
    tier: "coherent-10k",
    title: "青石巷",
    handwritten: true,
    characters: [
      { name: "林晚", role: "主角，盐镇人，后任城西出版社美术编辑" },
      { name: "林秀兰", role: "林晚的母亲，盐镇杂货铺老板" },
      { name: "沈砚", role: "林晚的表哥，雾港旧书修复师" },
      { name: "林蔓", role: "林晚的远房表妹，盐城茶馆老板" },
      { name: "陈屿", role: "城西出版社编辑，摄影展策展人" },
    ],
    places: ["盐镇", "盐城", "雾港", "城西的文化馆", "城东的画廊", "城西的出版社", "退潮后的滩涂", "旧码头", "盐镇中学"],
    objects: ["旧怀表", "老相机", "煤油灯", "贝壳"],
    chapters: [
      {
        number: 1,
        title: "海雾里的盐镇",
        anchors: [
          { id: "d1", category: "distant-recall", entity: "林晚", statement: "林晚出生在盐镇，那个海边小镇常年被海雾笼罩。" },
          { id: "d2", category: "distant-recall", entity: "林晚", statement: "她小时候最喜欢在退潮后的滩涂上捡贝壳。" },
        ],
      },
      {
        number: 2,
        title: "表哥的旧书铺",
        anchors: [
          { id: "d3", category: "cross-chapter-relation", entity: "沈砚", statement: "沈砚是林晚的表哥，母亲这边的亲戚，在雾港做旧书修复。" },
        ],
      },
      {
        number: 3,
        title: "表妹的茶馆",
        anchors: [
          { id: "d4", category: "similar-entity", entity: "林蔓", statement: "林蔓是林晚的远房表妹，三年前搬去了盐城，在城里开茶馆。" },
          { id: "d5", category: "similar-entity", entity: "盐城", statement: "盐城和盐镇只隔着一片海湾，名字相近，外地人常把两地搞混。" },
        ],
      },
      {
        number: 4,
        title: "母亲的杂货铺",
        anchors: [
          { id: "d6", category: "cross-chapter-relation", entity: "林秀兰", statement: "林晚的母亲叫林秀兰，在盐镇开着一间小杂货铺。" },
        ],
      },
      {
        number: 5,
        title: "讲台上的怀表",
        anchors: [
          { id: "d7", category: "multi-turn-recall", entity: "林晚", statement: "林晚在盐镇中学教语文，课间总把玩外婆留给她的旧怀表。" },
        ],
      },
      {
        number: 6,
        title: "辞职的决定",
        anchors: [
          { id: "d8", category: "version-conflict", entity: "林晚", statement: "林晚辞去了盐镇中学的工作，去了城西的出版社做美术编辑。" },
        ],
      },
      {
        number: 7,
        title: "城西的摄影展",
        anchors: [
          { id: "d9", category: "false-premise", entity: "林晚", statement: "朋友劝林晚把摄影展办在城东的画廊，她最后选了城西的文化馆，策展人是出版社编辑陈屿。" },
        ],
      },
    ],
    queries: [
      {
        id: "lc-coherent-01",
        category: "distant-recall",
        description: "远距召回：出生地埋在第一章开头，需跨越大量连贯叙事召回。",
        question: "林晚的出生地是哪里？",
        expect: {
          factBoundary: { mustContain: ["盐镇"], mustNegate: [] },
          wrongConclusions: ["出生在盐城"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章"],
          riskTags: ["distant-recall"],
        },
      },
      {
        id: "lc-coherent-02",
        category: "distant-recall",
        description: "远距召回：童年爱好埋在第一章。",
        question: "林晚小时候喜欢做什么？",
        expect: {
          factBoundary: { mustContain: ["捡贝壳"], mustNegate: [] },
          wrongConclusions: ["钓鱼", "游泳"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章"],
          riskTags: ["distant-recall"],
        },
      },
      {
        id: "lc-coherent-03",
        category: "cross-chapter-relation",
        description: "跨章关系：沈砚是表哥（第二章）+ 林秀兰是母亲（第四章），推出甥舅关系。",
        question: "沈砚和林秀兰是什么关系？",
        expect: {
          factBoundary: { mustContain: ["外甥"], mustNegate: [] },
          wrongConclusions: ["侄子", "儿子"],
          allowedUncertainty: [],
          evidenceLocations: ["第二章", "第四章"],
          riskTags: ["cross-chapter-relation"],
        },
      },
      {
        id: "lc-coherent-04",
        category: "cross-chapter-relation",
        description: "跨章关系：陈屿在第七章以编辑和策展人身份出现。",
        question: "陈屿是谁？",
        expect: {
          factBoundary: { mustContain: ["编辑"], mustNegate: [] },
          wrongConclusions: ["医生", "教师"],
          allowedUncertainty: [],
          evidenceLocations: ["第七章"],
          riskTags: ["cross-chapter-relation"],
        },
      },
      {
        id: "lc-coherent-05",
        category: "similar-entity",
        description: "相似实体：林蔓住盐城，与林晚住盐镇一字之差，需区分。",
        question: "林蔓住在哪里？",
        expect: {
          factBoundary: { mustContain: ["盐城"], mustNegate: [] },
          wrongConclusions: ["住在盐镇"],
          allowedUncertainty: [],
          evidenceLocations: ["第三章"],
          riskTags: ["similar-entity"],
        },
      },
      {
        id: "lc-coherent-06",
        category: "similar-entity",
        description: "相似实体：盐镇与盐城易混，林晚住盐镇而非盐城。",
        question: "林晚住在盐城吗？",
        expect: {
          factBoundary: { mustContain: ["盐镇"], mustNegate: ["住在盐城"] },
          wrongConclusions: ["住在盐城"],
          allowedUncertainty: [],
          evidenceLocations: ["第一章", "第三章"],
          riskTags: ["similar-entity"],
        },
      },
      {
        id: "lc-coherent-07",
        category: "version-conflict",
        description: "版本冲突：早期在盐镇中学教书（第五章），后来去了出版社（第六章），应依据最新事实。",
        question: "林晚现在在哪里工作？",
        expect: {
          factBoundary: { mustContain: ["出版社"], mustNegate: [] },
          wrongConclusions: ["在盐镇中学教书"],
          allowedUncertainty: [],
          evidenceLocations: ["第六章"],
          riskTags: ["version-conflict"],
        },
      },
      {
        id: "lc-coherent-08",
        category: "version-conflict",
        description: "版本冲突：工作已从盐镇中学变为出版社，应否定旧工作。",
        question: "林晚现在还在盐镇中学教书吗？",
        expect: {
          factBoundary: { mustContain: ["出版社"], mustNegate: ["在盐镇中学教书"] },
          wrongConclusions: ["还在盐镇中学"],
          allowedUncertainty: [],
          evidenceLocations: ["第五章", "第六章"],
          riskTags: ["version-conflict"],
        },
      },
      {
        id: "lc-coherent-09",
        category: "unknown-fact",
        description: "未知事实：材料从未提及林晚的丈夫。",
        question: "林晚的丈夫叫什么名字？",
        expect: {
          factBoundary: { mustContain: [], mustNegate: [] },
          wrongConclusions: [],
          allowedUncertainty: ["未知", "未提及"],
          evidenceLocations: ["全文"],
          riskTags: ["unknown-fact"],
        },
      },
      {
        id: "lc-coherent-10",
        category: "unknown-fact",
        description: "未知事实：材料未给出林晚的年龄。",
        question: "林晚今年多少岁？",
        expect: {
          factBoundary: { mustContain: [], mustNegate: [] },
          wrongConclusions: [],
          allowedUncertainty: ["未知", "未提及"],
          evidenceLocations: ["全文"],
          riskTags: ["unknown-fact"],
        },
      },
      {
        id: "lc-coherent-11",
        category: "false-premise",
        description: "错误前提纠正：问题误以为摄影展在城东的画廊，正确地点是城西的文化馆。",
        question: "林晚的摄影展是在城东的画廊举办的吗？",
        expect: {
          factBoundary: { mustContain: ["城西的文化馆"], mustNegate: ["在城东的画廊举办"] },
          wrongConclusions: ["在城东的画廊举办"],
          allowedUncertainty: [],
          evidenceLocations: ["第七章"],
          riskTags: ["false-premise"],
        },
      },
      {
        id: "lc-coherent-12",
        category: "multi-turn-recall",
        description: "多轮召回：经前置追问后召回怀表来源。",
        question: "林晚的怀表是谁留给她的？",
        steps: [{ text: "我之前问过林晚的怀表，你还记得吗？" }],
        expect: {
          factBoundary: { mustContain: ["外婆"], mustNegate: [] },
          wrongConclusions: ["母亲留给她的", "沈砚留给她的"],
          allowedUncertainty: [],
          evidenceLocations: ["第五章"],
          riskTags: ["multi-turn-recall"],
        },
      },
    ],
  },
};
