export interface AppDom {
  welcomePage: HTMLElement;
  newProjectPage: HTMLElement;
  editorPage: HTMLElement;
  btnNewProject: HTMLButtonElement;
  btnOpenProject: HTMLButtonElement;
  projectNameInput: HTMLInputElement;
  saveLocationInput: HTMLInputElement;
  btnBrowse: HTMLButtonElement;
  btnCancelNew: HTMLButtonElement;
  btnCreateProject: HTMLButtonElement;
  nameError: HTMLElement;
  locationError: HTMLElement;
  currentProjectName: HTMLElement;
  saveStatus: HTMLElement;
  btnSave: HTMLButtonElement;
  btnBackWelcome: HTMLButtonElement;
  tabWriting: HTMLButtonElement;
  tabFiles: HTMLButtonElement;
  tabSettings: HTMLButtonElement;
  moduleWriting: HTMLElement;
  moduleFiles: HTMLElement;
  moduleSettings: HTMLElement;
  editorTextarea: HTMLElement;
  currentDocToggle: HTMLButtonElement;
  currentDocumentName: HTMLElement;
  documentList: HTMLElement;
  writingEmptyState: HTMLElement;
  fmNewDocument: HTMLButtonElement;
  fmNewFolder: HTMLButtonElement;
  fmStatus: HTMLElement;
  fmFileTree: HTMLElement;
  fmOpenRecycleBin: HTMLButtonElement;
  fmRecycleBin: HTMLElement;
  fmBackFromRecycle: HTMLButtonElement;
  fmRecycleList: HTMLElement;
  paragraphStyle: HTMLSelectElement;
  btnBold: HTMLButtonElement;
  btnItalic: HTMLButtonElement;
  btnBulletList: HTMLButtonElement;
  btnOrderedList: HTMLButtonElement;
  btnToolbarUnderline: HTMLButtonElement;
  btnToolbarStrike: HTMLButtonElement;
  btnUndo: HTMLButtonElement;
  btnRedo: HTMLButtonElement;
  btnFind: HTMLButtonElement;
  btnMargin: HTMLButtonElement;
  btnFormatDrawer: HTMLButtonElement;
  formatToolbar: HTMLElement;
  formatDrawer: HTMLElement;
  btnFormatDrawerClose: HTMLButtonElement;
  btnUnderline: HTMLButtonElement;
  btnStrike: HTMLButtonElement;
  btnToggleCharacterSection: HTMLButtonElement;
  btnToggleParagraphSection: HTMLButtonElement;
  selectFontFamily: HTMLSelectElement;
  selectFontSize: HTMLSelectElement;
  inputTextColor: HTMLInputElement;
  btnClearTextColor: HTMLButtonElement;
  inputHighlight: HTMLInputElement;
  btnClearHighlight: HTMLButtonElement;
  btnClearCharacterFormat: HTMLButtonElement;
  btnAlignLeft: HTMLButtonElement;
  btnAlignCenter: HTMLButtonElement;
  btnAlignRight: HTMLButtonElement;
  btnAlignJustify: HTMLButtonElement;
  selectLineHeight: HTMLSelectElement;
  selectSpacingBefore: HTMLSelectElement;
  selectSpacingAfter: HTMLSelectElement;
  selectTextIndent: HTMLSelectElement;
  selectIndentLeft: HTMLSelectElement;
  selectIndentRight: HTMLSelectElement;
  btnClearParagraphFormat: HTMLButtonElement;
  findBar: HTMLElement;
  findInput: HTMLInputElement;
  findCaseSensitive: HTMLInputElement;
  btnFindPrev: HTMLButtonElement;
  btnFindNext: HTMLButtonElement;
  findCount: HTMLElement;
  replaceInput: HTMLInputElement;
  btnReplace: HTMLButtonElement;
  btnReplaceAll: HTMLButtonElement;
  btnFindClose: HTMLButtonElement;
  contextMenu: HTMLElement;
  btnCtxCut: HTMLButtonElement;
  btnCtxCopy: HTMLButtonElement;
  btnCtxPaste: HTMLButtonElement;
  btnCtxPastePlain: HTMLButtonElement;
  btnCtxLinkCreate: HTMLButtonElement;
  ctxLinkGroup: HTMLElement;
  btnCtxLinkOpen: HTMLButtonElement;
  btnCtxLinkEdit: HTMLButtonElement;
  btnCtxLinkRemove: HTMLButtonElement;
  linkPopover: HTMLElement;
  btnLinkOpen: HTMLButtonElement;
  btnLinkEdit: HTMLButtonElement;
  btnLinkRemove: HTMLButtonElement;
  apiBaseUrlInput: HTMLInputElement;
  apiBaseUrlError: HTMLElement;
  apiKeyInput: HTMLInputElement;
  apiKeyError: HTMLElement;
  modelNameInput: HTMLInputElement;
  modelNameError: HTMLElement;
  llmSaveStatus: HTMLElement;
  btnSaveConfig: HTMLButtonElement;
  btnTestConfig: HTMLButtonElement;
  btnBackConfig: HTMLButtonElement;
  btnToggleAi: HTMLButtonElement;
  aiPanel: HTMLElement;
  aiResponse: HTMLPreElement;
  aiConversation: HTMLElement;
  aiFollowUpForm: HTMLFormElement;
  aiFollowUpInput: HTMLTextAreaElement;
  aiFollowUpSend: HTMLButtonElement;
  leaveDialog: HTMLDialogElement;
  btnSaveAndLeave: HTMLButtonElement;
  btnDiscardAndLeave: HTMLButtonElement;
  btnCancelLeave: HTMLButtonElement;
}

function requireElement<T extends HTMLElement>(id: string): T {
  const element = document.getElementById(id);

  if (!element) {
    throw new Error(`Missing required element: #${id}`);
  }

  return element as T;
}

export function getAppDom(): AppDom {
  return {
    welcomePage: requireElement("welcome-page"),
    newProjectPage: requireElement("new-project-page"),
    editorPage: requireElement("editor-page"),
    btnNewProject: requireElement("btn-new-project"),
    btnOpenProject: requireElement("btn-open-project"),
    projectNameInput: requireElement("project-name"),
    saveLocationInput: requireElement("save-location"),
    btnBrowse: requireElement("btn-browse"),
    btnCancelNew: requireElement("btn-cancel-new"),
    btnCreateProject: requireElement("btn-create-project"),
    nameError: requireElement("name-error"),
    locationError: requireElement("location-error"),
    currentProjectName: requireElement("current-project-name"),
    saveStatus: requireElement("save-status"),
    btnSave: requireElement("btn-save"),
    btnBackWelcome: requireElement("btn-back-welcome"),
    tabWriting: requireElement("tab-writing"),
    tabFiles: requireElement("tab-files"),
    tabSettings: requireElement("tab-settings"),
    moduleWriting: requireElement("module-writing"),
    moduleFiles: requireElement("module-files"),
    moduleSettings: requireElement("module-settings"),
    editorTextarea: requireElement("editor-textarea"),
    currentDocToggle: requireElement("current-doc-toggle"),
    currentDocumentName: requireElement("current-document-name"),
    documentList: requireElement("document-list"),
    writingEmptyState: requireElement("writing-empty-state"),
    fmNewDocument: requireElement("fm-new-document"),
    fmNewFolder: requireElement("fm-new-folder"),
    fmStatus: requireElement("fm-status"),
    fmFileTree: requireElement("fm-file-tree"),
    fmOpenRecycleBin: requireElement("fm-open-recycle-bin"),
    fmRecycleBin: requireElement("fm-recycle-bin"),
    fmBackFromRecycle: requireElement("fm-back-from-recycle"),
    fmRecycleList: requireElement("fm-recycle-list"),
    paragraphStyle: requireElement("paragraph-style"),
    btnBold: requireElement("btn-bold"),
    btnItalic: requireElement("btn-italic"),
    btnBulletList: requireElement("btn-bullet-list"),
    btnOrderedList: requireElement("btn-ordered-list"),
    btnToolbarUnderline: requireElement("btn-toolbar-underline"),
    btnToolbarStrike: requireElement("btn-toolbar-strike"),
    btnUndo: requireElement("btn-undo"),
    btnRedo: requireElement("btn-redo"),
    btnFind: requireElement("btn-find"),
    btnMargin: requireElement("btn-margin"),
    btnFormatDrawer: requireElement("btn-format-drawer"),
    formatToolbar: requireElement("format-toolbar"),
    formatDrawer: requireElement("format-drawer"),
    btnFormatDrawerClose: requireElement("btn-format-drawer-close"),
    btnUnderline: requireElement("btn-underline"),
    btnStrike: requireElement("btn-strike"),
    btnToggleCharacterSection: requireElement("btn-toggle-character-section"),
    btnToggleParagraphSection: requireElement("btn-toggle-paragraph-section"),
    selectFontFamily: requireElement("select-font-family"),
    selectFontSize: requireElement("select-font-size"),
    inputTextColor: requireElement("input-text-color"),
    btnClearTextColor: requireElement("btn-clear-text-color"),
    inputHighlight: requireElement("input-highlight"),
    btnClearHighlight: requireElement("btn-clear-highlight"),
    btnClearCharacterFormat: requireElement("btn-clear-character-format"),
    btnAlignLeft: requireElement("btn-align-left"),
    btnAlignCenter: requireElement("btn-align-center"),
    btnAlignRight: requireElement("btn-align-right"),
    btnAlignJustify: requireElement("btn-align-justify"),
    selectLineHeight: requireElement("select-line-height"),
    selectSpacingBefore: requireElement("select-spacing-before"),
    selectSpacingAfter: requireElement("select-spacing-after"),
    selectTextIndent: requireElement("select-text-indent"),
    selectIndentLeft: requireElement("select-indent-left"),
    selectIndentRight: requireElement("select-indent-right"),
    btnClearParagraphFormat: requireElement("btn-clear-paragraph-format"),
    findBar: requireElement("find-bar"),
    findInput: requireElement("find-input"),
    findCaseSensitive: requireElement("find-case-sensitive"),
    btnFindPrev: requireElement("btn-find-prev"),
    btnFindNext: requireElement("btn-find-next"),
    findCount: requireElement("find-count"),
    replaceInput: requireElement("replace-input"),
    btnReplace: requireElement("btn-replace"),
    btnReplaceAll: requireElement("btn-replace-all"),
    btnFindClose: requireElement("btn-find-close"),
    contextMenu: requireElement("context-menu"),
    btnCtxCut: requireElement("ctx-cut"),
    btnCtxCopy: requireElement("ctx-copy"),
    btnCtxPaste: requireElement("ctx-paste"),
    btnCtxPastePlain: requireElement("ctx-paste-plain"),
    btnCtxLinkCreate: requireElement("ctx-link-create"),
    ctxLinkGroup: requireElement("ctx-link-group"),
    btnCtxLinkOpen: requireElement("ctx-link-open"),
    btnCtxLinkEdit: requireElement("ctx-link-edit"),
    btnCtxLinkRemove: requireElement("ctx-link-remove"),
    linkPopover: requireElement("link-popover"),
    btnLinkOpen: requireElement("link-open"),
    btnLinkEdit: requireElement("link-edit"),
    btnLinkRemove: requireElement("link-remove"),
    apiBaseUrlInput: requireElement("api-base-url"),
    apiBaseUrlError: requireElement("api-base-url-error"),
    apiKeyInput: requireElement("api-key"),
    apiKeyError: requireElement("api-key-error"),
    modelNameInput: requireElement("model-name"),
    modelNameError: requireElement("model-name-error"),
    llmSaveStatus: requireElement("llm-save-status"),
    btnSaveConfig: requireElement("btn-save-config"),
    btnTestConfig: requireElement("btn-test-config"),
    btnBackConfig: requireElement("btn-back-config"),
    btnToggleAi: requireElement("btn-toggle-ai"),
    aiPanel: requireElement("ai-panel"),
    aiResponse: requireElement("ai-response"),
    aiConversation: requireElement("ai-conversation"),
    aiFollowUpForm: requireElement("ai-follow-up-form"),
    aiFollowUpInput: requireElement("ai-follow-up-input"),
    aiFollowUpSend: requireElement("ai-follow-up-send"),
    leaveDialog: requireElement("leave-dialog"),
    btnSaveAndLeave: requireElement("btn-save-and-leave"),
    btnDiscardAndLeave: requireElement("btn-discard-and-leave"),
    btnCancelLeave: requireElement("btn-cancel-leave"),
  };
}
